export enum NotificationReason {
  LOGIN = 'LOGIN',
  PURCHASE = 'PURCHASE',
  CREATE_ACCOUNT = 'CREATE_ACCOUNT',
  TEST_WITH_URL = 'TEST_WITH_URL',
  TEST_WITHOUT_URL = 'TEST_WITHOUT_URL',
  PURCHASE_ERROR = 'PURCHASE ERROR',
}
