import { OrderConfirmRequest, OrderPreviewResponse } from './types';

export const orderPreviewRequest = {
  useDefault: true,
  setDefault: false,
  orderId: null,
  namespace: '0dabb0f14acf4fef84bd2b2bf3085dfc',
  country: null,
  countryName: null,
  orderComplete: null,
  orderError: null,
  orderPending: null,
  offers: ['cae9b411f608482a9c646f00daac9e46'],
  offerPrice: '',
};

export const orderPreviewResponse: OrderPreviewResponse = {
  affiliation: null,
  catalogResponse: {
    currencySymbolPlacement: 'LEFT',
    subscriptionSupported: true,
    code: 'US',
    displayName: 'UNITED STATES',
    ratingSystem: 'ESRB',
    embargoed: false,
    sellerOfRecord: 'EPIC',
    vatChargeRate: 0.0,
    ratingSystems: [],
    vatPercentage: 0.0,
    defaultCurrency: 'USD',
    vatIncluded: false,
    region: 'US',
    sellerOfRecordName: 'Epic Games, Inc.',
    paymentCurrency: 'USD',
  },
  country: 'US',
  countryName: 'United States',
  message: null,
  namespace: '0dabb0f14acf4fef84bd2b2bf3085dfc',
  offers: ['cae9b411f608482a9c646f00daac9e46'],
  orderComplete: false,
  orderError: false,
  orderId: null,
  orderPending: false,
  orderResponse: {
    orderType: 'PURCHASE',
    symbol: '$',
    country: 'US',
    agentUserName: 'anonymous',
    toUSDExchangeRate: 1.0,
    totalPrice: 0,
    accountIpCountry: 'US',
    resendReceiptForPublic: false,
    formattedTotalPrice: { amount: '0.00', symbol: '$', placement: 'f', decimals: 2, digits: 2 },
    formattedConvenienceFee: {
      amount: '0.00',
      symbol: '$',
      placement: 'f',
      decimals: 2,
      digits: 2,
    },
    paymentCurrencySymbol: '$',
    vatRate: 0.0,
    orderStatus: 'PREVIEW',
    epicAccountId: '6719b70f6aa14ee3aa86e542fb7f3118',
    salesChannel: 'epic-store-web-purchase',
    formattedPresentmentAmount: {
      amount: '0.00',
      symbol: '$',
      placement: 'f',
      decimals: 2,
      digits: 2,
    },
    canQuickPurchase: true,
    formattedBillingPaymentAmount: {
      amount: '0.00',
      symbol: '$',
      placement: 'f',
      decimals: 2,
      digits: 2,
    },
    taxStatus: 'NOT_APPLICABLE',
    totalTax: 0,
    isFree: true,
    coupons: [],
    walletPaymentAmount: 0,
    totalDiscounted: 0,
    resendReceiptForAdmin: false,
    useSplitPayment: false,
    currency: 'USD',
    formattedTotalTax: { amount: '0.00', symbol: '$', placement: 'f', decimals: 2, digits: 2 },
    rewardVoucher: null,
    fraudScore: 0,
    lastModifiedDate: '2020-12-20T23:56:40.663+0000',
    paymentCurrencyCode: 'USD',
    paymentCurrencyAmount: 0,
    accountIpAddress: '134.215.124.5',
    vat: 0,
    batchJobFailedRetryCount: 0,
    lineOffers: [
      {
        totalPrice: 0,
        formattedTotalPrice: {
          amount: '0.00',
          symbol: '$',
          placement: 'f',
          decimals: 2,
          digits: 2,
        },
        entitlementSource: 'AppEpicgamesCom',
        vatRate: 0.0,
        sellerName: 'Hidden Path',
        refundedRevenueWithoutTax: 0,
        revenueWithoutTax: 0,
        title: 'Defense Grid: The Awakening',
        formattedBasePrice: { amount: '9.99', symbol: '$', placement: 'f', decimals: 2, digits: 2 },
        offerType: 'BASE_GAME',
        basePayoutCurrencyCode: 'USD',
        sellerId: 'o-lr4ubnee8h8ya6fjmgfqy63uftabu6',
        formattedDiscountedPrice: {
          amount: '0.00',
          symbol: '$',
          placement: 'f',
          decimals: 2,
          digits: 2,
        },
        refundedBasePayoutPrice: 0,
        remainingDiscountPrice: 0,
        refundedConvenienceFee: 0,
        refundedTax: 0,
        initiatedBy: 'SELLER',
        basePrice: 999,
        formattedBasePayoutPrice: {
          amount: '0.00',
          symbol: '$',
          placement: 'f',
          decimals: 2,
          digits: 2,
        },
        unitPrice: 0,
        refundedDiscountPrice: 0,
        quantity: 1,
        vat: 0,
        formattedVoucherPrice: {
          amount: '0.00',
          symbol: '$',
          placement: 'f',
          decimals: 2,
          digits: 2,
        },
        refundedQuantity: 0,
        shareRate: 0,
        shareRateByDeveloper: 0,
        voucherDiscount: 0,
        namespaceDisplayName: 'Amaryllis',
        convenienceFee: 0,
        discountedPrice: 0,
        formattedTaxPrice: { amount: '0.00', symbol: '$', placement: 'f', decimals: 2, digits: 2 },
        namespace: '0dabb0f14acf4fef84bd2b2bf3085dfc',
        formattedUnitPrice: { amount: '0.00', symbol: '$', placement: 'f', decimals: 2, digits: 2 },
        offerId: 'cae9b411f608482a9c646f00daac9e46',
        taxPrice: 0,
        basePayoutPrice: 0,
        roleNames: [],
      },
    ],
    merchantGroup: 'EGS_MKT',
    creationDate: '2020-12-20T23:56:40.663+0000',
    formattedWalletPaymentAmount: {
      amount: '0.00',
      symbol: '$',
      placement: 'f',
      decimals: 2,
      digits: 2,
    },
    convenienceFee: 0,
    identityId: '6719b70f6aa14ee3aa86e542fb7f3118',
    fraud: false,
    billingPaymentAmount: 0,
    vatIncluded: false,
    paymentCurrencyExchangeRate: 1.0,
    formattedTotalDiscounted: {
      amount: '0.00',
      symbol: '$',
      placement: 'f',
      decimals: 2,
      digits: 2,
    },
    canSplitPayment: false,
  },
  paypalError: null,
  showCurrencyChangeMessage: false,
  syncToken: '53e1183a-6e95-4a39-b244-d0e2937852da',
  voucherList: null,
};

export const confirmOrderReqSample1: OrderConfirmRequest = {
  useDefault: true,
  setDefault: false,
  namespace: '4561b40e52584ac2bcf34bbd5c401480',
  country: 'US',
  countryName: 'United States',
  orderId: null,
  orderComplete: false,
  orderError: false,
  orderPending: false,
  offers: ['e9428ad618aa45f4b3371b8c8c4f9de9'],
  includeAccountBalance: false,
  totalAmount: 0,
  affiliateId: '',
  creatorSource: '',
  threeDSToken: '',
  voucherCode: null,
  eulaId: null,
  lineOffers: [
    {
      offerId: 'e9428ad618aa45f4b3371b8c8c4f9de9',
      title: 'Defense Grid: The Awakening',
      namespace: '4561b40e52584ac2bcf34bbd5c401480',
      upgradePathId: null,
    },
  ],
  useDefaultBillingAccount: true,
  syncToken: '7c004b4b-2403-4e04-b5aa-e957ab1da77d',
  canQuickPurchase: true,
};

export const confirmOrderReqSample2: OrderConfirmRequest = {
  useDefault: true,
  setDefault: false,
  namespace: '4561b40e52584ac2bcf34bbd5c401480',
  country: 'US',
  countryName: 'United States',
  orderId: null,
  orderComplete: false,
  orderError: false,
  orderPending: false,
  offers: ['e9428ad618aa45f4b3371b8c8c4f9de9'],
  includeAccountBalance: false,
  totalAmount: 0,
  affiliateId: '',
  creatorSource: '',
  threeDSToken: '',
  voucherCode: null,
  eulaId: null,
  lineOffers: [
    {
      offerId: 'e9428ad618aa45f4b3371b8c8c4f9de9',
      title: 'Defense Grid: The Awakening',
      namespace: '4561b40e52584ac2bcf34bbd5c401480',
      upgradePathId: null,
    },
  ],
  useDefaultBillingAccount: true,
  syncToken: '54780dc6-2798-4fcb-b4a3-16f1e7e43262',
  captchaToken:
    '7165eda99c06f1a67.1810703201|r=us-east-1|metabgclr=%23202020|maintxtclr=%23808080|mainbgclr=%23202020|guitextcolor=%23808080|metaiconclr=%23808080|meta_height=384|meta_width=340|meta=11|pk=B73BD16E-3C8E-9082-F9C7-FA780FF2E68B|at=40|atp=2|cdn_url=https://cdn.arkoselabs.com/fc|lurl=https://audio-us-east-1.arkoselabs.com|surl=https://epic-games-api.arkoselabs.com',
};

export const confirmOrderReqSample3: OrderConfirmRequest = {
  useDefault: true,
  setDefault: false,
  orderId: null,
  namespace: '0dabb0f14acf4fef84bd2b2bf3085dfc',
  country: 'US',
  countryName: 'United States',
  orderComplete: false,
  orderError: false,
  orderPending: false,
  offers: ['cae9b411f608482a9c646f00daac9e46'],
  includeAccountBalance: false,
  totalAmount: 0,
  affiliateId: '',
  creatorSource: '',
  threeDSToken: '',
  voucherCode: null,
  eulaId: null,
  lineOffers: [
    {
      offerId: 'cae9b411f608482a9c646f00daac9e46',
      title: 'Defense Grid: The Awakening',
      namespace: '0dabb0f14acf4fef84bd2b2bf3085dfc',
      upgradePathId: null,
    },
  ],
  useDefaultBillingAccount: true,
  syncToken: '83165834-fd7c-41d0-a6a7-590d9f7a5623',
  captchaToken:
    '9695fdfe4c229b3e7.0282928501|r=us-east-1|metabgclr=%23202020|maintxtclr=%23808080|mainbgclr=%23202020%3B|guitextcolor=%23808080|metaiconclr=%238a8a8a|meta_height=384|meta_width=340|meta=11|pk=B73BD16E-3C8E-9082-F9C7-FA780FF2E68B|at=40|sup=1|rid=42|atp=2|cdn_url=https://cdn.arkoselabs.com/fc|lurl=https://audio-us-east-1.arkoselabs.com|surl=https://epic-games-api.arkoselabs.com',
};

export const confirmOrderResponse = {
  cardinalInfo: null,
  cardinalLookUpResponse: null,
  confirmation: 'F2012202356515794',
  message: null,
  orderPending: null,
  receiptResponse: {
    orderType: 'PURCHASE',
    symbol: '$',
    country: 'US',
    agentUserName: 'anonymous',
    toUSDExchangeRate: 1.0,
    orderId: 'F2012202356515794',
    totalPrice: 0,
    accountIpCountry: 'US',
    resendReceiptForPublic: true,
    formattedTotalPrice: { amount: '0.00', symbol: '$', placement: 'f', decimals: 2, digits: 2 },
    formattedConvenienceFee: {
      amount: '0.00',
      symbol: '$',
      placement: 'f',
      decimals: 2,
      digits: 2,
    },
    paymentCurrencySymbol: '$',
    vatRate: 0.0,
    orderStatus: 'COMPLETED',
    epicAccountId: '6719b70f6aa14ee3aa86e542fb7f3118',
    salesChannel: 'epic-store-web-purchase',
    formattedPresentmentAmount: {
      amount: '0.00',
      symbol: '$',
      placement: 'f',
      decimals: 2,
      digits: 2,
    },
    taxStatus: 'NOT_APPLICABLE',
    totalTax: 0,
    coupons: [],
    totalDiscounted: 0,
    resendReceiptForAdmin: true,
    currency: 'USD',
    formattedTotalTax: { amount: '0.00', symbol: '$', placement: 'f', decimals: 2, digits: 2 },
    rewardVoucher: null,
    fraudScore: 0,
    completedAt: '2020-12-20T23:56:51.205+0000',
    comments: 'Free Checkout',
    lastModifiedDate: '2020-12-20T23:56:51.205+0000',
    paymentCurrencyCode: 'USD',
    paymentCurrencyAmount: 0,
    accountIpAddress: '134.215.124.5',
    vat: 0,
    batchJobFailedRetryCount: 0,
    lineOffers: [
      {
        totalPrice: 0,
        formattedTotalPrice: {
          amount: '0.00',
          symbol: '$',
          placement: 'f',
          decimals: 2,
          digits: 2,
        },
        entitlementSource: 'AppEpicgamesCom',
        vatRate: 0.0,
        sellerName: 'Hidden Path',
        refundedRevenueWithoutTax: 0,
        revenueWithoutTax: 0,
        title: 'Defense Grid: The Awakening',
        formattedBasePrice: { amount: '9.99', symbol: '$', placement: 'f', decimals: 2, digits: 2 },
        offerType: 'BASE_GAME',
        basePayoutCurrencyCode: 'USD',
        sellerId: 'o-lr4ubnee8h8ya6fjmgfqy63uftabu6',
        formattedDiscountedPrice: {
          amount: '0.00',
          symbol: '$',
          placement: 'f',
          decimals: 2,
          digits: 2,
        },
        refundedBasePayoutPrice: 0,
        remainingDiscountPrice: 0,
        refundedConvenienceFee: 0,
        refundedTax: 0,
        initiatedBy: 'SELLER',
        basePrice: 999,
        formattedBasePayoutPrice: {
          amount: '0.00',
          symbol: '$',
          placement: 'f',
          decimals: 2,
          digits: 2,
        },
        unitPrice: 0,
        refundedDiscountPrice: 0,
        quantity: 1,
        offerItems: [
          {
            itemId: 'dd2f150f062f4d9eaea1079022ddc30c',
            entitlementRevoked: false,
            entitlementId: '5b44e057becd4c8ab0da2d24c833f622',
            namespace: '0dabb0f14acf4fef84bd2b2bf3085dfc',
            entitlementName: 'dd2f150f062f4d9eaea1079022ddc30c',
          },
        ],
        vat: 0,
        formattedVoucherPrice: {
          amount: '0.00',
          symbol: '$',
          placement: 'f',
          decimals: 2,
          digits: 2,
        },
        refundedQuantity: 0,
        shareRate: 0,
        shareRateByDeveloper: 0,
        voucherDiscount: 0,
        namespaceDisplayName: 'Amaryllis',
        convenienceFee: 0,
        discountedPrice: 0,
        formattedTaxPrice: { amount: '0.00', symbol: '$', placement: 'f', decimals: 2, digits: 2 },
        namespace: '0dabb0f14acf4fef84bd2b2bf3085dfc',
        formattedUnitPrice: { amount: '0.00', symbol: '$', placement: 'f', decimals: 2, digits: 2 },
        offerId: 'cae9b411f608482a9c646f00daac9e46',
        taxPrice: 0,
        basePayoutPrice: 0,
      },
    ],
    merchantGroup: 'EGS_MKT',
    creationDate: '2020-12-20T23:56:51.099+0000',
    convenienceFee: 0,
    identityId: '6719b70f6aa14ee3aa86e542fb7f3118',
    fraudDecision: 'APPROVE',
    fraud: false,
    vatIncluded: false,
    paymentCurrencyExchangeRate: 1.0,
    invoiceId: 'F623184815',
    formattedTotalDiscounted: {
      amount: '0.00',
      symbol: '$',
      placement: 'f',
      decimals: 2,
      digits: 2,
    },
  },
  syncToken: null,
};
